---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhou.
--- DateTime: 2023/6/28 15:12
---

-- 比较线程标识与锁中的标识是否一致
-- 这里的 KEYS[1] 就是锁的key，这里的ARGV[1] 就是当前线程标示
if (redis.call('GET', KEYS[1]) == ARGV[1]) then
    -- 一致，则删除锁
    return redis.call('del', KEYS[1])
end
-- 不一致，则直接返回
return 0
